version: '3'
services:
  nginx:
   container_name: test-nginx
   restart: always
   build: ./nginx/
   ports:
   - 8080:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app

  app:
    container_name: test-app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run 
